// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjW3LkeVW9ySdVugITCnt1m9U4cSsIaAQ',
    appId: '1:128563381461:web:43aba59cb0bc3e5fa74e5c',
    messagingSenderId: '128563381461',
    projectId: 'cs23-project',
    authDomain: 'cs23-project.firebaseapp.com',
    storageBucket: 'cs23-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7JpOm8nwOs933vu5HMkXsAZ3I1dEDqs8',
    appId: '1:128563381461:android:410583e496a3a70ea74e5c',
    messagingSenderId: '128563381461',
    projectId: 'cs23-project',
    storageBucket: 'cs23-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkuw2AMyTXy6uH1qomw2TIsLrk8AFXE1w',
    appId: '1:128563381461:ios:56811d88b673800aa74e5c',
    messagingSenderId: '128563381461',
    projectId: 'cs23-project',
    storageBucket: 'cs23-project.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkuw2AMyTXy6uH1qomw2TIsLrk8AFXE1w',
    appId: '1:128563381461:ios:56811d88b673800aa74e5c',
    messagingSenderId: '128563381461',
    projectId: 'cs23-project',
    storageBucket: 'cs23-project.appspot.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjW3LkeVW9ySdVugITCnt1m9U4cSsIaAQ',
    appId: '1:128563381461:web:13e24dcea4f2841aa74e5c',
    messagingSenderId: '128563381461',
    projectId: 'cs23-project',
    authDomain: 'cs23-project.firebaseapp.com',
    storageBucket: 'cs23-project.appspot.com',
  );

}